---
settings:
  name: E-Series
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação da série E
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
  - title: Começar
    entries:
    - title: Descubra os sistemas da Série E
      url: "/task-discover-e-series.html"
  - title: Gerenciar sistemas da série E
    entries:
    - title: Visualize seus sistemas da Série E
      url: "/task-view-e-series.html"
    - title: Remover um sistema do NetApp Console
      url: "/task-remove-e-series.html"
  - title: Conhecimento e suporte
    entries:
    - title: Registre-se para obter suporte
      url: "/task-support-registration.html"
    - title: Obter ajuda
      url: "/task-get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
